name: 'Kube-score-py'
description: 'Kubernetes object analysis with recommendations for improved reliability and security.'
author: 'ixxeL'
inputs:
  format:
    description: 'Format result. [human,ci,json]'
    required: false
    default: 'human'
  verbose:
    description: 'Enable verbose output.'
    required: false
    default: 'true'
  kube-version:
    description: 'Setting the kubernetes-version will affect the checks ran against the manifests.'
    required: false
    default: 'v1.18'
  warning-fail:
    description: 'Exit with code 1 in case of warnings.'
    required: false
    default: 'false'  
  exit-zero:
    description: 'Force exit 0 code'
    required: false
    default: 'true'
  working-dir:
    description: 'file to scan'
    required: false
    default: './*.yaml'

runs:
  using: "composite"
  steps:
    - id: kube-score-py
      run: |
        import subprocess
        import sys
        from colorama import init, Fore, Back, Style
        sys.stdout.isatty = sys.stderr.isatty = lambda: True

        init(autoreset=True)
        print(f"{Fore.BLUE}{Style.BRIGHT}[ STEP - IaC security scan ] > IaC code security scan with Kube-score.")
        print(sys.stdout.isatty())

        try:
          subprocess.run(["kube-score", "version"], shell=False, check=True, stderr=subprocess.PIPE)
        except subprocess.CalledProcessError as e:
          print(e.stderr)
          sys.exit(1)

        try:
          subprocess.run(["kube-score score deploy-test.yaml"], shell=True, check=True, stderr=subprocess.PIPE)
        except subprocess.CalledProcessError as e:
          print(e.stderr)
          sys.exit(1)

      
      shell: python
      env:
        PY_COLOR: 1
        FORCE_COLOR: 3

# Fore: BLACK, RED, GREEN, YELLOW, BLUE, MAGENTA, CYAN, WHITE, RESET.
# Back: BLACK, RED, GREEN, YELLOW, BLUE, MAGENTA, CYAN, WHITE, RESET.
# Style: DIM, NORMAL, BRIGHT, RESET_A